- name: Check project
  shell: bash
  run: |
    set -eux

    echo "===== ROOT ====="
    ls -la

    echo "===== PROJECT ====="
    test -f makefile
    echo "Makefile found"

- name: Build TIPA
  shell: bash
  run: |
    set -eux

    export THEOS="$GITHUB_WORKSPACE/theos"

    make clean || true
    make package FINALPACKAGE=1

- name: Show build output
  shell: bash
  run: |
    set -eux

    echo "===== BUILD OUTPUT ====="
    find . -type f \( -name "*.tipa" -o -name "*.deb" \) -print
